# ---------------------------------------------------------------------------------------------------------------------
# Scan configuration
# ---------------------------------------------------------------------------------------------------------------------
download-external-modules: true
evaluate-variables: true
framework: all
# ---------------------------------------------------------------------------------------------------------------------
# Checkov output formatting
# ---------------------------------------------------------------------------------------------------------------------
compact: true
skip-fixes: true
no-guide: true
output: cli
quiet: true
